server:
  port: 8099

# 不需要进行弹窗认证
security:
  basic:
    enabled: false

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bootdo?useUnicode=true&characterEncoding=utf8
    username: root
    password:

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # 指定Mapper.xml文件位置
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  # 配置短名
  typeAliasesPackage: com.bootdo